---
title: "Datenveröffentlichungen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Das WZB hat eine Kooperation mit dem GESIS-Leibniz-Institut für Sozialwissenschaften zur Publikation von WZB-Forschungsdaten im Fachrepositorium SowiDataNet|datorium. Die folgende Übersicht enthält die Forschungsdaten, die WZB-Wissenschaftler*innen im Rahmen dieser WZB-Sammlung bei GESIS veröffentlicht haben.

```{r cars, include=FALSE}
# set working directory:
setwd("/Users/dross/Nextcloud/R")

# install and load packages:
# install.packages("dplyr", repos = "http://cran.us.r-project.org")
library(dplyr)
# install.packages("reactable", repos = "http://cran.us.r-project.org")
library(reactable)

# load data from *.csv
data_final <- read.csv("data_cite.csv")

# prepare data:
data_tab <- data_final %>%
  arrange(desc(year)) %>%
  transmute(year, title, name2, version_cor,
            DOI2 = paste('<a href="', doi_vector, '">', doi_vector, '</a>', sep = "")) %>%
  rename(Jahr = year, Titel = title, `Autor*innen` = name2, Version = version_cor,
         DOI = DOI2)

```


```{r pressure, echo=FALSE}

# Erzeuge Tabelle:
reactable(data_tab, filterable = TRUE,
                    searchable = TRUE,
                    bordered = TRUE, 
                    striped = TRUE,
                    highlight = TRUE,
                    defaultPageSize = 10, showPageSizeOptions = TRUE, 
                    showSortable = TRUE,
                    pageSizeOptions = c(10, 20, 30, 40, 50),
                    defaultSortOrder = "desc",
                    columns = list(
                    DOI = colDef(html = TRUE, minWidth = 170),
                    Titel = colDef(minWidth = 180, resizable = TRUE),
                    `Autor*innen` = colDef(minWidth = 180, resizable = TRUE),
                    Jahr = colDef(maxWidth = 80),
                    Version = colDef(maxWidth = 90)
                    ))

```